Nav_links:
  type: list
  default: "Site Feedback,Discussions about this community, ideas for improvement, questions that need to be answered!,/c/site-feedback|Contest!, Ever wanted to just win something? Now here's your chance!, /t/5"
  description:
    en: "Comma delimited in this order: display name,description,URL. Display name is the text that shows on the menu. Description is the help text that shows on hover. URL is the path for the link."
